[tool.black]
line-length = 100
target-version = ["py313"]

[tool.ruff]
line-length = 100
target-version = "py313"
src = ["src", "tests"]

[tool.ruff.lint]
extend-select = ["W", "I"]  # pycodestyle warns + import sorting
extend-ignore = ["E501"]    # Black owns line length

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q --color=yes --cov=src --cov-report=term-missing"

[tool.mypy]
python_version = "3.13"
strict = false
ignore_missing_imports = true
