name: tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Tip: 3.11 is broadly supported. If you want 3.13, change to '3.13'
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Lint
        run: |
          ruff check .
          black --check .

      - name: Run tests
        run: |
          pytest -q

      - name: Debug workspace
        shell: bash
        run: |
          set -euxo pipefail
          echo "PWD: $(pwd)"
          echo "Commit: $(git rev-parse --short HEAD)"
          ls -la
          echo -n "requirements.txt present? "; if [ -f requirements.txt ]; then echo yes; else echo NO; fi
          echo -n "requirements-dev.txt present? "; if [ -f requirements-dev.txt ]; then echo yes; else echo NO; fi

      - name: Install deps
        shell: bash
        run: |
          set -euxo pipefail
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then
            python -m pip install -r requirements-dev.txt
          else
            echo "::warning file=requirements-dev.txt,line=1::requirements-dev.txt not found; skipping dev deps"
          fi
